version: "3"

dotenv:
  - .env

vars:
  BIN_DIR: bin
  APP_NAME: artshare
  APP_PATH: ./cmd/artshare
  MIGRATIONS_DIR: migrations-postgres
  MIGRATE_CMD: go run -tags 'postgres'
    github.com/golang-migrate/migrate/v4/cmd/migrate@latest

tasks:
  build:
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -o {{.BIN_DIR}}/{{.APP_NAME}} {{.APP_PATH}}

  check:
    cmds:
      - task: lint
      - task: test

  clean:
    cmds:
      - rm -rf {{.BIN_DIR}}/*

  deps:
    # TODO: Make from Docker container
    cmds:
      - go install -tags 'postgres'
        github.com/golang-migrate/migrate/v4/cmd/migrate@latest

  lint:
    # TODO: Make from Docker container
    cmds:
      - golangci-lint run --fix --timeout 5m ./...

  migrate-postgres:
    # TODO: Make from Docker container
    cmds:
      - '{{.MIGRATE_CMD}} -database "$DATABASE_URL" -path {{.MIGRATIONS_DIR}}
        up'

  migrate-up-postgres:
    # TODO: Make from Docker container
    cmds:
      - '{{.MIGRATE_CMD}} -database "$DATABASE_URL" -path {{.MIGRATIONS_DIR}}
        up 1'

  migrate-down-postgres:
    # TODO: Make from Docker container
    cmds:
      - '{{.MIGRATE_CMD}} -database "$DATABASE_URL" -path {{.MIGRATIONS_DIR}}
        down 1'

  run:
    deps: [build] # TODO: Make from Docker container
    cmds:
      - ./{{.BIN_DIR}}/{{.APP_NAME}}

  test:
    cmds:
      - go test ./...

  start-cluster:
    # TODO: startt DB + application using Docker Compose

  stop-cluster:
    # TODO: stop DB + application

  test-integration:
  # TODO: start container with integration test code and run tests against the running application container
